const categories = [
  { name: "Artificial Intelligence", route: "cs.AI" },
  { name: "Computation and Language", route: "cs.CL" },
  { name: "Computational Complexity", route: "cs.CC" },
  { name: "Computational Engineering, Finance, and Science", route: "cs.CE" },
  { name: "Computational Geometry", route: "cs.CG" },
  { name: "Computer Science and Game Theory", route: "cs.GT" },
  { name: "Computer Vision and Pattern Recognition", route: "cs.CV" },
  { name: "Computers and Society", route: "cs.CY" },
  { name: "Cryptography and Security", route: "cs.CR" },
  { name: "Data Structures and Algorithms", route: "cs.DS" },
  { name: "Databases", route: "cs.DB" },
  { name: "Digital Libraries", route: "cs.DL" },
  { name: "Discrete Mathematics", route: "cs.DM" },
  { name: "Distributed, Parallel, and Cluster Computing", route: "cs.DC" },
  { name: "Emerging Technologies", route: "cs.ET" },
  { name: "Formal Languages and Automata Theory", route: "cs.FL" },
  { name: "General Literature", route: "cs.GL" },
  { name: "Graphics", route: "cs.GR" },
  { name: "Hardware Architecture", route: "cs.AR" },
  { name: "Human-Computer Interaction", route: "cs.HC" },
  { name: "Information Retrieval", route: "cs.IR" },
  { name: "Information Theory", route: "cs.IT" },
  { name: "Logic in Computer Science", route: "cs.LO" },
  { name: "Machine Learning", route: "cs.LG" },
  { name: "Mathematical Software", route: "cs.MS" },
  { name: "Multiagent Systems", route: "cs.MA" },
  { name: "Multimedia", route: "cs.MM" },
  { name: "Networking and Internet Architecture", route: "cs.NI" },
  { name: "Neural and Evolutionary Computing", route: "cs.NE" },
  { name: "Numerical Analysis", route: "cs.NA" },
  { name: "Operating Systems", route: "cs.OS" },
  { name: "Other Computer Science", route: "cs.OH" },
  { name: "Performance", route: "cs.PF" },
  { name: "Programming Languages", route: "cs.PL" },
  { name: "Robotics", route: "cs.RO" },
  { name: "Social and Information Networks", route: "cs.SI" },
  { name: "Software Engineering", route: "cs.SE" },
  { name: "Sound", route: "cs.SD" },
  { name: "Symbolic Computation", route: "cs.SC" },
  { name: "Systems and Control", route: "cs.SY" },
];

export default categories;
